function y = doFilter_FIR_lowpass(x,Fs)
%DOFILTER_FIR_LOWPASS2 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 11-Oct-2017 13:24:58

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.


    
% The following code is used to design the filter coefficients:
% % Equiripple Lowpass filter designed using the FIRPM function.
%
% % All frequency values are in Hz.
%
Fpass = 5;               % Passband Frequency
Fstop = 8;               % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.001;           % Stopband Attenuation
dens  = 20;              % Density Factor
%
% % Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
%
% % Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});


% y = step(Hd,x);
y=filtfilt(b,1,x);


% [EOF]
