%	OVERVIEW:
%       Demo of HRV Toolbox Analysis on Standardized Data generated by
%       RRGEN
%   INPUT:
%       No input necessary. RRGEN data is generated within this script
%   OUTPUT:
%       HRV Metrics
%   DEPENDENCIES & LIBRARIES:
%       HRV_toolbox https://github.com/cliffordlab/hrv_toolbox
%       WFDB Matlab toolbox https://github.com/ikarosilva/wfdb-app-toolbox
%       WFDB Toolbox https://physionet.org/physiotools/wfdb.shtml
%   REFERENCE: 
%	REPO:       
%       https://github.com/cliffordlab/hrv_toolbox
%   ORIGINAL SOURCE AND AUTHORS:     
%       Main script written by Adriana N. Vest
%       Dependent scripts written by various authors 
%       (see functions for details)       
%	COPYRIGHT (C) 2017
%   LICENSE:    
%       This software is offered freely and without warranty under 
%       the GNU (v3 or later) public license. See license file for
%       more information
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all; clc; close all;
HRVparams = InitializeHRVparams('demo'); % include the project name

% Check existence of Output data folders and add to search path

HRVparams.writedata = [HRVparams.writedata filesep 'RRgenData'];
if ~exist(HRVparams.writedata, 'dir')
   mkdir(HRVparams.writedata)
end
addpath(HRVparams.writedata)


%% 1. Generate Data

rr = rrgen(HRVparams.demo.length,HRVparams.demo.pe,HRVparams.demo.pn,HRVparams.demo.seed);
t = cumsum(rr);

%% 2. Preprocess RR Data - Using HRV Toolbox
% Remove noise, Remove ectopy, Don't detrend (yet)
[NN, tNN, fbeats] = RRIntervalPreprocess(rr,t,[], HRVparams);

%% 3. Calculate Windows
RRwindowStartIndices = CreateWindowRRintervals(tNN, NN, HRVparams);


%% 4. Calculate time domain HRV metrics - Using HRV Toolbox
[NNmean,NNmedian,NNmode,NNvariance,NNskew,NNkurt, SDNN, NNiqr, ...
    RMSSD,pnn50,btsdet,avgsqi,fbeatw, RRwindowStartIndices] = ...
    EvalTimeDomainHRVstats(NN,tNN,[],HRVparams,RRwindowStartIndices);

%% 6. Frequency domain HRV metrics (LF HF TotPow)
%       All Inputs in Seconds
%%% TO DO: Remove necessity of creating phantom beats with lomb 
%%% TO DO: Only should return these metrics for 5 min segments

[ulf, vlf, lf, hf, lfhf, ttlpwr, methods, fdflag, window] = ...
   EvalFrequencyDomainHRVstats(NN,tNN, [],HRVparams,RRwindowStartIndices);

%% 7. PRSA
try
    [ac,dc,~] = prsa(NN, tNN, [], RRwindowStartIndices, HRVparams);
catch
    ac = NaN;
    dc = NaN;
    error_flag(i_patient) = subjectids(i_patient);
end

%% 8. SDANN and SDNNi
[SDANN, SDNNI] = CalcSDANN(RRwindowStartIndices, tNN, NN(:),HRVparams);

%% 10. Save Results
% Uncomment the following lines for All Results
results = [RRwindowStartIndices(:),ac(:),dc(:),...
    ulf(:),vlf(:),lf(:),hf(:),lfhf(:),ttlpwr(:),fdflag(:),...
    NNmean(:),NNmedian(:),NNmode(:),...
    NNvariance(:),NNskew(:),NNkurt(:),SDNN(:),NNiqr(:),RMSSD(:),...
    pnn50(:),btsdet(:),fbeatw(:)];

col_titles = {'t_win','ac','dc','ulf','vlf','lf','hf','lfhf',...
    'ttlpwr','fdflag','NNmean','NNmedian','NNmode','NNvar','NNskew',...
    'NNkurt','SDNN','NNiqr','RMSSD','pnn50','beatsdetected','corrected_beats'};

% results = [NNmean(:), NNmedian(:)];
% col_titles = {'NN Mean','NNmedian'};

% Generates Output - Never comment out
resFilenameHRV = GenerateHRVresultsOutput('demo',RRwindowStartIndices,...
    results,col_titles, [],HRVparams, tNN, NN);


%% 11 Compare generated output file with the reference one
        
currentFile = [HRVparams.writedata filesep resFilenameHRV '.csv'];
referenceFile = ['ReferenceOutput' filesep 'StandardizedData_HRV_allwindows.csv'];
testHRV = CompareOutput(currentFile,referenceFile);

if testHRV
    fprintf('** DemoStandardizedData: TEST SUCCEEDED ** \n ')
     fprintf('A file named %s.csv \n has been saved in %s \n', ...
    resFilenameHRV, HRVparams.writedata);
else
    fprintf('** DemoStandardizedData: TEST FAILED ** \n')
end
